build: false

environment:
  matrix:
    - PYTHON_VERSION: 3.6
      MINICONDA: C:\Miniconda3

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda config --add channels conda-forge
  - conda install conda-build
  - conda-build ./installer/conda
  - conda install --use-local orange3-single-cell
  - conda list --export --explicit --md5

test_script:
  # - nosetests
