# Python package
# Create and test a Python package on multiple Python versions and systems.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master


jobs:

  - job: 'Linux'
    pool:
      vmImage: 'ubuntu-16.04'
    strategy:
      matrix:
        Python36:
          python.version: '3.6'
        # Python37:
          # python.version: '3.7'
      # maxParallel: 2

    steps:
      - template: templates/install_add_on.yml
      - script: |
          pip install pytest pytest-cov
          catchsegv xvfb-run -a -s "-screen 0 1280x1024x24" \
            pytest orangecontrib/single_cell/tests --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
        displayName: 'Run pytest'
      - task: PublishTestResults@2
        condition: succeededOrFailed()
        inputs:
          testResultsFiles: '**/test-results.xml'
          testRunTitle: 'Python $(python.version)'
      - task: PublishCodeCoverageResults@1
        inputs:
          codeCoverageTool: Cobertura
          summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
          reportDirectory: '$(System.DefaultWorkingDirectory)/**/htmlcov'

      - script: |
          python setup.py sdist bdist_wheel
        displayName: 'Build packages'
      - task: CopyFiles@2
        inputs:
          contents: dist/**
          targetFolder: $(Build.ArtifactStagingDirectory)
      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: $(Build.ArtifactStagingDirectory)


#  - job: 'macOS'
#    pool:
#      vmImage: 'macOS-10.13'
#    strategy:
#      matrix:
#        Python36:
#          python.version: '3.6'
#        # Python37:
#          # python.version: '3.7'
#      # maxParallel: 2
#
#    steps:
#      - template: templates/install_add_on.yml
#      - script: |
#          pip install pytest pytest-cov
#          pytest orangecontrib/single_cell/tests --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
#        displayName: 'Run pytest'
#      - task: PublishTestResults@2
#        inputs:
#          testResultsFiles: '**/test-results.xml'
#          testRunTitle: 'Python $(python.version)'
#        condition: succeededOrFailed()


#  - job: 'Windows'
#    pool:
#      vmImage: 'vs2017-win2016'
#    strategy:
#      matrix:
#        Python36:
#          python.version: '3.6'
#        # Python37:
#          # python.version: '3.7'
#      # maxParallel: 2
#
#    steps:
#      - template: templates/install_add_on.yml
#      - script: |
#          pip install pytest pytest-cov
#          pytest orangecontrib/single_cell/tests --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
#        displayName: 'Run pytest'
#      - task: PublishTestResults@2
#        inputs:
#          testResultsFiles: '**/test-results.xml'
#          testRunTitle: 'Python $(python.version)'
#        condition: succeededOrFailed()




# pip install pytest pytest-cov
# pytest orangecontrib/single_cell/tests --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html

#    - task: PublishTestResults@2
#      inputs:
#        testResultsFiles: '**/test-results.xml'
#        testRunTitle: 'Python $(python.version)'
#      condition: succeededOrFailed()