parameters:
  # defaults for any parameters that aren't specified
  name: ''
  vmImage: ''

jobs:

- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
      # Python37:
        # python.version: '3.7'
    # maxParallel: 2


    - script: |
        python setup.py -v test
      displayName: 'Run pytest'

      # pip install pytest pytest-cov
      # pytest orangecontrib/single_cell/tests --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html

#    - task: PublishTestResults@2
#      inputs:
#        testResultsFiles: '**/test-results.xml'
#        testRunTitle: 'Python $(python.version)'
#      condition: succeededOrFailed()