parameters:
  orange_version: 'released'

steps:

- script: |
    python -m pip install --upgrade pip setuptools wheel
    pip install numpy==1.16.4
  displayName: 'Install build tools'

- ${{ if in(parameters.orange_version, 'dev') }}:
  - script: |
      pip install https://github.com/biolab/orange3/archive/master.zip
      pip install https://github.com/biolab/orange3-bioinformatics/archive/master.zip
    displayName: 'Install dev version of Orange'
    continueOnError: false

- script: |
    pip install -r requirements.txt
    pip install PyQt5~=5.9.0
    pip install sphinx recommonmark
  displayName: 'Install requirements'
  continueOnError: false

- script: pip install -e .
  displayName: 'Install Orange3-SingleCell'
  continueOnError: false
